name: Get Latest Release Info

on:
  release:
    types: [published]

jobs:
  get_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest release info
        run: |
          RELEASE_INFO=$(curl --header "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          TITLE=$(echo $RELEASE_INFO | jq -r .name)
          BODY=$(echo $RELEASE_INFO | jq -r .body)
          APK_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url')
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "BODY=$BODY" >> $GITHUB_ENV
          echo "APK_URL=$APK_URL" >> $GITHUB_ENV

      - name: Save info to file
        run: |
          echo "{\"title\": \"$TITLE\", \"body\": \"$BODY\", \"apk_url\": \"$APK_URL\"}" > version.txt

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add version.txt
          git commit -m "Update version.txt with latest release info"
          git push
