name: Get Latest Release Info

on:
  release:
    types: [published]

jobs:
  get_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GH_TOKEN }}

      - name: Update latest release info
        run: |
          RELEASE_INFO=$(curl --header "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/latest)
          TITLE=$(echo $RELEASE_INFO | jq -r .name)
          BODY=$(echo $RELEASE_INFO | jq -r .body)
          URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name | endswith(".apk")) | .browser_download_url')
          printf "TITLE=%s\n" "$TITLE" >> $GITHUB_ENV
          printf "BODY=%s\n" "$BODY" >> $GITHUB_ENV
          printf "APK_URL=%s\n" "$APK_URL" >> $GITHUB_ENV
          curl -X PATCH --location "${{ secrets.LOCATION }}" \
          -H "Content-Type: application/json" \
          -d '{"url":"$URL","body":"$BODY","title":"$TITLE"}' \
          --basic --user "${{ secrets.USER }}"
   
